name: Execute notebooks

on: [push]

jobs:
  run-notebooks:
    strategy:
      fail-fast: true
      matrix:
          python-version: ['3.9', '3.11']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install poetry
      run: pipx install poetry==1.8.3

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "poetry"

    - name: Install dependencies
      run: poetry install
    
    - run: poetry run python -m ipykernel install --user --name anoexpress
    - run: papermill workflow/notebooks/plot-gene-expression.ipynb ci.ipynb -k anoexpress
    - run: papermill workflow/notebooks/plot-families-expression.ipynb ci2.ipynb -k anoexpress
    - run: papermill workflow/notebooks/expression-candidates.ipynb ci3.ipynb -k anoexpress
    - run: papermill workflow/notebooks/enrichment.ipynb ci4.ipynb -k anoexpress
    - run: papermill workflow/notebooks/utility-functions.ipynb ci5.ipynb -k anoexpress
