name: Execute notebooks

on: [push]

jobs:
  run-notebooks:
    strategy:
      fail-fast: true
      matrix:
          python-version: ['3.8', '3.10']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version:  ${{ matrix.python-version }}
    - run: python3 -m pip install anoexpress malariagen_data nbformat ipykernel papermill nbconvert
    - run: python -m ipykernel install --user --name anoexpress
    - run: papermill workflow/notebooks/plot-gene-expression.ipynb ci.ipynb -k anoexpress
    - run: papermill workflow/notebooks/plot-families-expression.ipynb ci2.ipynb -k anoexpress
    - run: papermill workflow/notebooks/expression-candidates.ipynb ci3.ipynb -k anoexpress
    - run: papermill workflow/notebooks/enrichment.ipynb ci4.ipynb -k anoexpress
    - run: papermill workflow/notebooks/utility-functions.ipynb ci5.ipynb -k anoexpress
